@startuml
package "メンター募集" {
  object メンター募集 {
    タイトル
    予算
    詳細
    カテゴリ
    タグ名
    募集スタイル
    ディスクリプション
    応募期間
    ステータス
  }
}
note top of メンター募集
  タイトル:255文字以内
  詳細:3000文字以内
  カテゴリ:1つ
  タグ名:複数OK
  募集スタイル:単発or継続
  ディスクリプション:2000文字以内
  予算from:1000円以上の数値
  予算to:1000円以上の数値、予算fromよりも大きい数字
  応募期間
  ステータス:公開or中止
end note

package "メンティー" {
  object メンティー {
    メンティーID
    名前
    e-mail
  }
}

package "メンター" {
  object メンター {
    メンターID
    名前
    e-mail
    プラン
  }
}

package "プラン" {
  object プラン {
    プランID
    タグ名
    タイトル
    内容
    カテゴリ
    ステータス
  }
}

package "メンター募集提案" {
  object メンター募集提案 {
    メンター募集ID
    内容
  }
}
note bottom of メンター募集提案
  メンター募集ID
  内容:3000文字以内
end note

package "タグ" {
  object タグ {
    タグID
    名前
  }
}

メンター募集 "1" --* "1..n" メンター募集提案
メンター募集 "1..n" --* "1..n" タグ
プラン "1..n" --* "1..n" タグ
メンティー "1..n" --* "1..n" メンター募集
メンティー "1..n" --* "1..n" プラン
メンター "1..n" --* "1..n" プラン
メンター "1..n" --* "1..n" メンター募集提案

@enduml