@startuml Helpa on Diagram

package "メンター募集" {
  object メンター募集 {
    募集ID
    ユーザID
    タイトル
    予算
    詳細
    カテゴリ
    List<タグID>
    募集スタイル
    ディスクリプション
    応募期間
    ステータス
  }
}
note top of メンター募集
  募集ID
  ユーザID
  タイトル:255文字以内
  予算from:1000円以上の数値
  詳細:3000文字以内
  カテゴリ:1つ
  タグID:複数OK
  募集スタイル:単発or継続
  ディスクリプション:2000文字以内
  予算to:1000円以上の数値、予算fromよりも大きい数字
  応募期間
  ステータス:公開or中止
end note

package "プラン" {
  object プラン {
    プランID
    ユーザID
    List<タグID>
    タイトル
    内容
    カテゴリ
    ステータス
    募集スタイル
    予算
  }
}
note bottom of プラン
  プランID
  ユーザID
  タグID:複数OK
  タイトル:255文字以内
  内容:3000文字以内
  カテゴリ:1つ
  ステータス:公開or中止
  募集スタイル:単発or継続
  予算from:1000円以上の数値
end note

package "契約" {
  object 契約 {
    契約ID
    契約リクエストID
    メッセージ
  }
}
note top of 契約
  契約ID
  契約リクエストID
  メッセージ:3000文字以内
end note

package "メンター募集提案" {
  object メンター募集提案 {
    メンター募集ID
    ユーザID
    提案メッセージ
  }
}
note bottom of メンター募集提案
  メンター募集ID
  ユーザID
  提案メッセージ:3000文字以内
  ※ここはあくまでプランを売り込むメッセージとなる（プラン誘導）
  ※契約時は必ずプラン契約を経由して契約となる
end note

package "タグ" {
  object タグ {
    タグID
    名前
  }
}
note bottom of タグ
  タグID
  名前:50文字
end note

package "ユーザ登録" {
  object ユーザ {
    ユーザID
    名前
    e-mail
    List<経歴>
    Liset<スキル>
  }
  object スキル {
    タグID
  }
  object 経歴 {
    経歴詳細
  }
}
note top of ユーザ
  ユーザID
  名前:50文字以内
  e-mail:125文字以内
end note

package "契約リクエスト" {
  object 契約リクエスト {
    契約リクエストID
    プランID
    プラン金額
    ユーザID
  }
}

メンター募集 "1" <-- "1..n" メンター募集提案
ユーザ "1" <-- "1..n" メンター募集提案
メンター募集 "1..n" *-- "1..n" タグ
プラン "1..n" *-- "1..n" タグ
ユーザ "1" *-- "1..n" スキル
ユーザ "1" *-- "1..n" 経歴
スキル "1..n" *-- "1..n" タグ
契約 "1" --> "1" 契約リクエスト
契約リクエスト "1..n" --> "1" プラン
契約リクエスト "1..n" --> "1" ユーザ

@enduml