version: '3'

services:
  db:
    container_name: mysql
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
      LANG: ja_JP.UTF-8
    ports:
        - ${DB_PORT}:3306
    volumes:
        - ./my.cnf:/etc/mysql/conf.d/my.cnf
